# Generated by Django 4.2.21 on 2025-05-17 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='about',
        ),
    ]
